# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d7f75a7a68cf0be2e5b2e0bb504377b495a336e592a305b53c959c4fa85d991c2c874def89bf648fb6650a23391925b2812eca26489900264e7201ad2d3e30d

test:
  secret_key_base: 67d8722545c63dbc84ea7c453516a3a45fe7b45f3db006af990d622c6ba0e5b4e435a1a4bb6a1ebe72cef0c61e902039149d6b72a381ae6b4ed545d25a5fc672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
